sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node
  before_deploy:
    - docker login -u brocklife  -p Godisgreat4me
  
  deploy:
    provider: script
    script: docker push  brocklife/node
    on:
      branch: master
